### ISSUE TITLE
Mixin `fontFaceCustom` points to wrong font files

### ISSUE THREAD

**Issue by Phillip9587** [DecliningLotus/fontsource#415]
**Describe the bug**
`fontFaceCustom` Mixin produces a wrong css output. 

**To Reproduce**

1. `npm i sass @fontsource/roboto` 
2. Create a `styles.scss` file and insert the following code:

```scss
@use 'node_modules/@fontsource/roboto/scss/mixins' as Roboto;

@include Roboto.fontFaceCustom($weight: 300);
@include Roboto.fontFaceCustom($weight: 700);
```

3. compile with `npx sass styles.scss styles.css`
4. See the following css output in `styles.css`

 ```css 
@font-face {
  font-family: "Roboto";
  font-style: normal;
  font-display: swap;
  font-weight: 300;
  src: url("~@fontsource/roboto/files/roboto-latin-400-normal.woff2") format("woff2"), url("~@fontsource/roboto/files/roboto-latin-400-normal.woff") format("woff");
}
@font-face {
  font-family: "Roboto";
  font-style: normal;
  font-display: swap;
  font-weight: 700;
  src: url("~@fontsource/roboto/files/roboto-latin-400-normal.woff2") format("woff2"), url("~@fontsource/roboto/files/roboto-latin-400-normal.woff") format("woff");
}
```

**Expected behavior**
The src urls are pointing to the wrong src files when changing the weight. They always point to the default weight files. 

The expected output is: 

```css
@font-face {
  font-family: "Roboto";
  font-style: normal;
  font-display: swap;
  font-weight: 300;
  src: url("~@fontsource/roboto/files/roboto-latin-300-normal.woff2") format("woff2"), url("~@fontsource/roboto/files/roboto-latin-300-normal.woff") format("woff");
}
@font-face {
  font-family: "Roboto";
  font-style: normal;
  font-display: swap;
  font-weight: 700;
  src: url("~@fontsource/roboto/files/roboto-latin-700-normal.woff2") format("woff2"), url("~@fontsource/roboto/files/roboto-latin-700-normal.woff") format("woff");
}
```
