### ISSUE TITLE
Font Request / Bug: Noto Emoji includes Numbers

### ISSUE THREAD

**Issue by NoonRightsWarriorBehindHovering** [DecliningLotus/fontsource#582]
**Font Name**
Noto Emoji (Already included) 

**Link to font source**
https://github.com/googlefonts/noto-emoji

**Describe the bug**
Inclusion of Noto currently adds the Number Range U+30-39 which adds Spacing to Numbers (aforementioned Unicode Range).
This problem seems to be present in upstream too.
I'm unsure if this is something you would be willing to maintain though, given that the repository only generates the fonts and retrieves unicode characters from google fonts.

**To Reproduce**

1. Use Font
2. Apply to Text with content '1'
3. See Spacing

**Expected behavior**
Spacing should not be included or atleast there should be a file provided, which can be included that excludes the given Range.

**Screenshots**
Available in issue 395 (Upstream), see below

**Link to font license**
[Apache-2](https://github.com/googlefonts/noto-emoji/blob/main/LICENSE)

**Additional context**
The following Issues are in upstream already:

https://github.com/googlefonts/noto-emoji/issues/218
https://github.com/googlefonts/noto-emoji/issues/395

A Workaround exists. For example in my Project i need three Fonts (Fira Code, Chivo and Lato). Each context (code, main, heading) uses a global variable for applicable fonts (r-${context}-font). I created a dummy font for each of those fonts that includes only numbers. I specify that before any other fonts i use. Then i use Noto to include emoji codepoints followed by the general "normal" font.

This is kind of reductive and seems easily solveable.

```css
:root {
    --global-code-font: "Fira Code";
    --global-main-font: "Chivo";
    --global-heading-font: "Lato";
    --global-emoji-font: "Noto Emoji";

    --global-code-font-num: "Fira Code Numbers Only";
    --global-main-font-num: "Chivo Numbers Only";
    --global-heading-font-num: "Lato Numbers Only";

    --r-code-font: var(--global-code-font-num), var(--global-emoji-font), var(--global-code-font);
    --r-main-font: var(--global-main-font-num), var(--global-emoji-font), var(--global-main-font);
    --r-heading-font: var(--global-heading-font-num), var(--global-emoji-font), var(--global-heading-font);
}

pre {
    font-family: var(--r-code-font);
}
```

```css
@font-face {
    font-family: "Fira Code Numbers Only";
    unicode-range: U+30-39;

    /* Copied and adapted from node_modules/@fontsource/fira-code/index.css */
    font-style: normal;
    font-display: swap;
    font-weight: 400;
    src: url('node_modules/@fontsource/fira-code/files/fira-code-latin-400-normal.woff2') format('woff2'), url('node_modules/@fontsource/fira-code/files/fira-code-all-400-normal.woff') format('woff');
}

@font-face {
    font-family: "Chivo Numbers Only";
    unicode-range: U+30-39;

    /* Copied and adapted from node_modules/@fontsource/chivo/index.css */
    font-style: normal;
    font-display: swap;
    font-weight: 400;
    src: url('node_modules/@fontsource/chivo/files/chivo-latin-400-normal.woff2') format('woff2'), url('node_modules/@fontsource/chivo/files/chivo-all-400-normal.woff') format('woff');
}

@font-face {
    font-family: "Lato Numbers Only";
    unicode-range: U+30-39;

    /* Copied and adapted from node_modules/@fontsource/lato/index.css */
    font-style: normal;
    font-display: swap;
    font-weight: 400;
    src: url('node_modules/@fontsource/lato/lato-latin-400-normal.woff2') format('woff2'), url('node_modules/@fontsource/lato/files/lato-all-400-normal.woff') format('woff');
}
```
