### ISSUE TITLE
Italics for Hanken Grotesk variable font

### ISSUE THREAD

**Issue by krzysztofjeziorny** [DecliningLotus/fontsource#660]
### Describe the bug

Compiling variable "[Hanken Grotesk](https://github.com/fontsource/fontsource/tree/main/fonts/google/hanken-grotesk)" with a [scss mixin](https://github.com/fontsource/fontsource/blob/main/fonts/google/hanken-grotesk/scss/mixins.scss) `fontFaceVariable` creates the code for `-normal.woff2` paths as expected. The paths to `-italic.woff2` variants are omitted.

### Steps to Reproduce

- all font files are present (for available subsets, types and styles)
- using the scss mixin.scss file with the [`fontFaceVariable`](https://github.com/fontsource/fontsource/blob/47c760ca7053c6b1e0fad811d8f307a0f6205af8/fonts/google/hanken-grotesk/scss/mixins.scss#L70) mixin

```scss
@include fontFaceVariable;
```

creates css for normal style fonts as expected. 

Not so for italics. I've tried setting:
```scss
em, i { $style: italic; }
// or
em {
  $fontNameVariable: "Hanken GroteskVariable";
  $style: italic;
  $woff2Path: "#{$fontDir}/#{$fontId}-#{$defSubset}-variable-#{$type}-#{$style}.woff2";  
  @include fontFaceVariableCustom;
}
```
however it doesn't brings me any closer to italics.

### Expected behavior

Am I missing some setting or import? Please excuse if it's not a bug but my own error.

### OS

Debian 11

### Browser

sass 1.60.0, gulp-sass 5.1.0

**Comment by jwr1** [comment]
You can't define a `@font-face` inside an element, so I'm not sure exactly what you're trying to do, but this works for me:
```scss
@include fontFaceVariable($style: italic);
```

If you need to import both the `normal` and the `italic` styles, try this:
```scss
  @include fontFaceVariable();
  @include fontFaceVariable($style: italic);
```

**Comment by jwr1** [comment]
If you're trying to make `em` elements italic, you'll need to `@include` the mixins above the styles and then set the `font-style` and `font-family` properties in the element:
```scss
@use '@fontsource/hanken-grotesk/scss/mixins' as hankeGrotesk;

@include hankeGrotesk.fontFaceVariable(); // Only if you need the normal style
@include hankeGrotesk.fontFaceVariable($style: italic);

em {
  font-family: 'Hanke Grotesk';
  font-style: italic;
}
```
