### ISSUE TITLE
--fontsource-display variable does not work

### ISSUE THREAD

**Issue by schmist** [DecliningLotus/fontsource#726]
### Describe the bug

CSS variables (as `--fontsource-display` described [here](https://fontsource.org/docs/getting-started/display)) seem not to work when used in an `@font-face` statement. See also [here](https://stackoverflow.com/questions/58752373/custom-css-properties-in-font-face.).

### Steps to Reproduce

As described here: https://fontsource.org/docs/getting-started/display. Declared variable is not honored.

### Expected behavior

Declared variable should be honored (seems not possible).

### Version

5.0.1

### OS

Linux

### Browser

Chrome

**Comment by ayuhito** [comment]
This is extremely unfortunate since it seems like no browsers seem to support custom properties in `@font-face` for undocumented reasons. Yet they support it in selectors like `@keyframes` 🤷 

I think we'll have to revert this change to use `swap` as a default. I still do want to offer an escape hatch, so once I have time I could investigate if there is an option where users can write their own `@font-face` statements and directly link to the font files themselves.

e.g. does referencing `node_modules` like this work in Webpack or Vite? Will it successfully rewrite the URLs?
```css
@font-face {
  font-family: 'Abel';
  font-style: normal;
  font-display: optional;
  font-weight: 400;
  src: url(/node_modules/@fontsource/abel/files/abel-latin-400-normal.woff2) format('woff2'), url(/node_modules/@fontsource/abel/files/abel-latin-400-normal.woff) format('woff');
}
```

The URL might also be prefixed with `@` or `~`, I'm not too sure.
