### ISSUE TITLE
@fontsource/fredoka-one missing woff files

### ISSUE THREAD

**Issue by Bartozzz** [DecliningLotus/fontsource#899]
### Describe the bug

The `./files/fredoka-one-all-400-normal.woff)` file from `index.css` does not exist.

```css
/* fredoka-one-latin-400-normal */
@font-face {
  font-family: 'Fredoka One';
  font-style: normal;
  font-display: var(--fontsource-display, swap);
  font-weight: 400;
  src: url(./files/fredoka-one-latin-400-normal.woff2) format('woff2'), url(./files/fredoka-one-all-400-normal.woff) format('woff');
  unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;
}
```

<img width="358" alt="image" src="https://github.com/fontsource/fontsource/assets/6741707/aebfa365-874d-429b-8052-b63f3cb7e121">

### Steps to Reproduce

Install `"@fontsource/fredoka-one": "5.0.5"`

### Version

5.0.5

### OS

All

### Browser

All
