### ISSUE TITLE
Update npm README for Work Sans font

### ISSUE THREAD

**Issue by kazzkiq** [DecliningLotus/fontsource#942]
<img width="766" alt="Screenshot 2024-02-13 at 18 20 08" src="https://github.com/fontsource/fontsource/assets/1953194/71328185-10f8-4008-a99f-8998e4e4ea80">

### Describe the bug

Work Sans font usage is being described as:

```css
body {
  font-family: "Work Sans";
}
```

When it should be:

```css
body {
  font-family: "Work Sans Variable";
}
```

### Steps to Reproduce

1. Open [@fontsource/work-sans](https://www.npmjs.com/package/@fontsource/work-sans) in npm
2. Check the font usage CSS example.
