### ISSUE TITLE
material-icons is missing the additional CSS class again

### ISSUE THREAD

**Issue by anentropic** [DecliningLotus/fontsource#976]
### Describe the bug

same as https://github.com/fontsource/fontsource/issues/152 which said that it was expected to be included here

...but it seems to be broken again: https://github.com/fontsource/font-files/blob/main/fonts/icons/material-icons/index.css

the Google source has a `.material-icons` class https://fonts.googleapis.com/icon?family=Material+Icons
```css
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

this is a necessary part of using the font as per: https://developers.google.com/fonts/docs/material_icons#setup_method_2_self_hosting

### Steps to Reproduce

`npm install @fontsource/material-icons`

try to use the icons as recommended `<span class="material-icons">face</span>`
